In [1]:
all_attributes=["Acceleration", "Balance", "Jumping", "Stamina", "Strength", "Vision"]

In [5]:
player_attributes=[{'Composure': 95, 'Balance': 63, 'Sliding tackle': 23}, {'Positioning': 93, 'Curve': 89, 'Finishing': 95, 'Marking': 13, 'Shot power': 85, 'Short passing': 88}, {'Reactions': 88, 'Shot power': 80, 'Marking': 21, 'Sliding tackle': 33, 'Strength': 53}, {'Acceleration': 88, 'Crossing': 77, 'Positioning': 92}, {'Finishing': 13, 'Marking': 10, 'Positioning': 12, 'Ball control': 48}, {'Curve': 77, 'GK kicking': 12, 'Positioning': 91}, {'Reactions': 88, 'Long passing': 51, 'Stamina': 40, 'Curve': 21, 'Short passing': 50, 'Marking': 13}, {'Volleys': 79, 'Free kick accuracy': 79, 'Acceleration': 93, 'Balance': 91}, {'Short passing': 90, 'Jumping': 32, 'Composure': 85, 'Ball control': 89, 'Aggression': 60}, {'Stamina': 72, 'Interceptions': 20, 'Strength': 85}]

In [6]:
d=[]
r=[]
c=[]
r_n=-1
for i in player_attributes:
    r_n+=1
    c_n=-1
    for j in all_attributes:
        c_n+=1
        if j in i:
            d.append(i[j])
            r.append(r_n)
            c.append(c_n)
print(d,r,c)

[63, 53, 88, 40, 93, 91, 32, 72, 85] [0, 2, 3, 6, 7, 7, 8, 9, 9] [1, 4, 0, 3, 0, 1, 2, 3, 4]


In [14]:
import numpy as np
import numpy.linalg as la

In [22]:
import math

In [28]:
x=1.234444444
len(x)

TypeError: object of type 'float' has no len()

In [32]:
while(x!=int(x)):
    x=x*10
int(math.log(x,10)+1)

1.2344444440000002e+16


In [37]:
import numpy as np
import numpy.linalg as la
import math
x=np.array([1/3,1/52345])

def di(x):
    while(x!=int(x)):
        x=x*10
    return int(math.log(x,10)+1)

correct_digits=0
for i in x:
    correct_digits+=di(i)

In [38]:
correct_digits

33

In [39]:
abs(-12)

12

In [42]:
len(str(1/52345*100000000000000000000000000))

22

In [63]:
def di(x):
    if x!=0:
        i=0
        while(x!=int(x)):
            x=x*10
            i+=1
        return i
    else:
        return 0

In [68]:
l=[]
for i in a:
    l.append(di(i))
max(l)

17

In [51]:
a=np.array([1/2,3/34,5/6,8/7])
a_n=np.array([1/23,3/4,4,8/7])

In [70]:
abs((a-a_n)/a)

array([0.91304348, 7.5       , 3.8       , 0.        ])

In [52]:
sum(a==a_n)

1

In [53]:
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [54]:
x=np.array([1,4])

In [56]:
np.multiply(A,x)

array([[ 1,  8],
       [ 3, 16]])

In [57]:
x[x>3]

array([4])

In [77]:
2.614482923250975e-07*10000001600.541441

2614.4833417098016

In [78]:
math.log(2.614482923250975e-07*10000001600.541441,10)

3.4173858790489944

In [71]:
log10(100)

NameError: name 'log10' is not defined

In [80]:
x=1.858515496956238e-08*9999998367.105076

In [83]:
x=100000000000+x

In [84]:
math.log(x,10)

11.000000000807141