In [1]:
a={1,2,123,314,1232}

In [7]:
A=[1,2,{}]

In [1]:
import numpy as np

In [11]:
B = np.array([2.2, 2, 8.1, 9])

In [16]:
A = [1, 2, 3, {}]

In [17]:
type(A[2])

int

In [18]:
A = 9
B = 3.33
C = 2
D = C + A
E = B - 9

In [22]:
type(E)

float

In [24]:
b = "Welcoma to CS 357"
b[6] = "e"
print(b)

TypeError: 'str' object does not support item assignment

In [25]:
A = [3,4,5,6,7,8,9,10,11]

In [26]:
A.pop(6)

9

In [27]:
A

[3, 4, 5, 6, 7, 8, 10, 11]

In [28]:
print(['Hello!'] * 2)

['Hello!', 'Hello!']


In [32]:
a = [1, 2, 3, 4]
b = a
a.append(5)
b.append(5)
print(a, b)

[1, 2, 3, 4, 5, 5] [1, 2, 3, 4, 5, 5]


In [33]:
a = [1, 2, 3, 4]
b = a
a.append(5)

In [44]:
def foo(x):
    x = ['abc','def']
    return id(x)
q = ['abc', 'def']
print(id(q) == foo(q))

False


In [41]:
q = ['abc', 'def']
id(q)

2207534217408

In [46]:
John = 'computer_science'
Tim = John
Tim += ', math'
Anna = ['electrical']
Julie = Anna
Julie += ['physics']
print(Tim,John, Anna)

computer_science, math computer_science ['electrical', 'physics']


In [47]:
John =2
Tim = John
Tim +=1
Anna = ['electrical']
Julie = Anna
Julie += ['physics']
print(Tim,John, Anna)

3 2 ['electrical', 'physics']


In [59]:
A=np.array([[1,2,3],[2,3,4],[3,4,5]])
r=A[0]
A[0]=A[2]
A[2]=r
A

array([[3, 4, 5],
       [2, 3, 4],
       [3, 4, 5]])

In [58]:
A=np.array([[1,2,3],[2,3,4],[3,4,5]])
A

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [67]:
def a(x):
    x.append('m')
def s(x):
    x=['t']
    x.append('e')
j=['c']
t=j
a(t)
s(j)
print(j,t)

['c', 'm'] ['c', 'm']


In [74]:
def s(x):
    x=['12345']
    x.append('e')
p=['1']
a(p)
p

['1', 'm']

In [73]:
def f(a):
    a = 4
    print(a)
b = 3
f(b)

4


In [83]:
A = [1,2,3,4]
B = A
C = A

B.append(5)
C = C + [6]

In [84]:
A,B

([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])

In [85]:
a = np.arange(1,10)
a[::-3] - a[3:6:1]

array([ 5,  1, -3])

In [86]:
a[::-3] 

array([9, 6, 3])

In [88]:
a[3:6:1]

array([4, 5, 6])

In [90]:
a[-2:]

array([8, 9])

In [11]:
A=np.array(range(27))
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [12]:
A=A.reshape(3,9)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [10]:
A.transpose()[:,1]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [13]:
nums = np.arange(10)
A = np.zeros(5, dtype=int)
for i in range(5):
    A[i] = nums[2*i]
A

array([0, 2, 4, 6, 8])

In [43]:
A=np.array(range(72))
A=A.reshape(8,9)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71]])

In [47]:
A.T

array([[ 0,  9, 18, 27, 36, 45, 54, 63],
       [ 1, 10, 19, 28, 37, 46, 55, 64],
       [ 2, 11, 20, 29, 38, 47, 56, 65],
       [ 3, 12, 21, 30, 39, 48, 57, 66],
       [ 4, 13, 22, 31, 40, 49, 58, 67],
       [ 5, 14, 23, 32, 41, 50, 59, 68],
       [ 6, 15, 24, 33, 42, 51, 60, 69],
       [ 7, 16, 25, 34, 43, 52, 61, 70],
       [ 8, 17, 26, 35, 44, 53, 62, 71]])

In [20]:
A.swapaxes(0,1)

array([[ 0,  9, 18, 27, 36, 45, 54, 63],
       [ 1, 10, 19, 28, 37, 46, 55, 64],
       [ 2, 11, 20, 29, 38, 47, 56, 65],
       [ 3, 12, 21, 30, 39, 48, 57, 66],
       [ 4, 13, 22, 31, 40, 49, 58, 67],
       [ 5, 14, 23, 32, 41, 50, 59, 68],
       [ 6, 15, 24, 33, 42, 51, 60, 69],
       [ 7, 16, 25, 34, 43, 52, 61, 70],
       [ 8, 17, 26, 35, 44, 53, 62, 71]])

In [22]:
A.reshape(9,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69, 70, 71]])

In [24]:
np.transpose(A)

array([[ 0,  9, 18, 27, 36, 45, 54, 63],
       [ 1, 10, 19, 28, 37, 46, 55, 64],
       [ 2, 11, 20, 29, 38, 47, 56, 65],
       [ 3, 12, 21, 30, 39, 48, 57, 66],
       [ 4, 13, 22, 31, 40, 49, 58, 67],
       [ 5, 14, 23, 32, 41, 50, 59, 68],
       [ 6, 15, 24, 33, 42, 51, 60, 69],
       [ 7, 16, 25, 34, 43, 52, 61, 70],
       [ 8, 17, 26, 35, 44, 53, 62, 71]])

In [25]:
a=[1,2,3,4,5]

In [26]:
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [38]:
A=np.array(range(5))

In [30]:
sum(A>2)

2

In [31]:
A

array([0, 1, 2, 3, 4])

In [32]:
B=(1,2,3)

In [33]:
A.flatten()

array([0, 1, 2, 3, 4])

In [34]:
A=[0,0,1,3,4]

In [35]:
np.unique(A)

array([0, 1, 3, 4])

In [39]:
A.astype(float)

array([0., 1., 2., 3., 4.])

In [41]:
A.resize(B)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [42]:
A.sort()

In [50]:
A+A

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16],
       [ 18,  20,  22,  24,  26,  28,  30,  32,  34],
       [ 36,  38,  40,  42,  44,  46,  48,  50,  52],
       [ 54,  56,  58,  60,  62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98, 100, 102, 104, 106],
       [108, 110, 112, 114, 116, 118, 120, 122, 124],
       [126, 128, 130, 132, 134, 136, 138, 140, 142]])

In [51]:
i = 0
while i < 3:
    print(i)
    i
    print(i+1)

SyntaxError: invalid syntax (<ipython-input-51-1886864a9e87>, line 4)