In [1]:
import numpy as np

In [2]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [3]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [4]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 2)

array([[0, 0, 3],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])