In [1]:
import numpy as np
import numpy.linalg as la

### 1

In [8]:
X = np.array([[2.265, -1.257, -1.448], [-1.647, -2.122, 0.861], [1.860, -0.398, 0.507], [0.233, -0.531, 0.595]])
mean=np.array([X[:,0].mean(),X[:,1].mean(),X[:,2].mean()])
X-mean

array([[ 1.58725, -0.18   , -1.57675],
       [-2.32475, -1.045  ,  0.73225],
       [ 1.18225,  0.679  ,  0.37825],
       [-0.44475,  0.546  ,  0.46625]])

### 3

In [18]:
S = np.array([[9.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 6.4, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 6.3, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 3.8, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 2.6, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]])
s=np.diag(S)
s

array([9.1, 6.4, 6.3, 3.8, 2.6, 1.1, 1. ])

In [20]:
(9.1+6.4+6.3)/sum(s)

0.7194719471947194

### 4

In [8]:
X = np.array([[0.1532171101, 2.7204860136, 1.8175093363, -0.2313442325], [-2.4973611655, -0.6983164820, 0.6018921554, 2.5936758749], [0.2593975869, -1.2107478502, 0.7680743825, 0.8387740655], [2.7279655895, 0.9667363641, -0.0235160052, -2.3703813711], [-0.2801087897, -0.8704200692, -1.7459381653, -1.3767273962], [0.4738030773, 2.2808128107, -1.0641076005, 0.5685557253], [-0.8369134085, -3.1885507870, -0.3539141031, -0.0225526659]])
U = np.array([[-0.3610451636, -0.4798074788, -0.3289440573, 0.5421269521], [0.5079245523, -0.4705889139, 0.0729256170, 0.0450159057], [0.1792944680, 0.0122891649, -0.4179703355, -0.5104710086], [-0.5467189474, 0.3743012472, -0.2615292562, -0.1530500163], [0.0327588790, 0.4195553300, 0.4924151990, 0.4451673611], [-0.2679811475, -0.2607767700, 0.6106131853, -0.4617844524], [0.4557673592, 0.4050274207, -0.1675103522, 0.0929952583]])
S = np.array([[5.9345726738, 0.0000000000, 0.0000000000, 0.0000000000], [0.0000000000, 4.6011457992, 0.0000000000, 0.0000000000], [0.0000000000, 0.0000000000, 2.5791442829, 0.0000000000], [0.0000000000, 0.0000000000, 0.0000000000, 1.4250937085]])
Vt = np.array([[-0.5537543491, -0.7035873188, -0.0224541384, 0.4447660255], [0.3359888345, -0.6261789992, -0.3809984596, -0.5914824916], [-0.2957618672, 0.3123576878, -0.8991540653, 0.0804957122], [-0.7021342762, 0.1236827421, 0.2141446996, -0.6677215625]])

In [9]:
X@Vt[:2,:].T

array([[-2.14264876, -2.20766417],
       [ 3.01431517, -2.1652482 ],
       [ 1.06403605,  0.05654424],
       [-3.24454333,  1.72221461],
       [ 0.19440995,  1.93043524],
       [-1.5903536 , -1.19987194],
       [ 2.70478452,  1.86359022]])

In [2]:
U = np.array([[-0.3, -0.2, -0.2, 0.5, 0.0, 0.0, 0.1, -0.2, 0.1, 0.2, 0.0, 0.2], [-0.3, -0.2, 0.0, 0.1, 0.1, 0.4, 0.3, 0.4, -0.3, -0.6, -0.1, 0.0], [-0.2, -0.3, -0.1, -0.1, -0.3, 0.1, 0.0, -0.1, 0.0, -0.1, 0.5, -0.2], [0.0, -0.3, -0.3, -0.1, 0.5, -0.1, -0.3, 0.0, 0.2, 0.0, -0.1, 0.1], [-0.3, -0.3, -0.1, 0.0, -0.3, 0.1, -0.4, -0.1, -0.4, 0.3, -0.1, 0.2], [-0.5, 0.1, -0.1, 0.0, -0.1, -0.4, -0.3, 0.0, 0.4, -0.3, -0.1, -0.1], [0.3, 0.0, 0.2, -0.1, 0.1, 0.0, -0.2, -0.4, -0.3, -0.3, -0.3, 0.1], [-0.1, -0.2, 0.5, -0.2, -0.1, 0.1, 0.2, -0.2, 0.2, 0.1, -0.1, 0.0], [-0.3, 0.2, 0.2, -0.5, 0.0, -0.2, 0.2, 0.0, 0.2, -0.1, 0.0, 0.0], [-0.1, 0.3, -0.3, -0.2, 0.1, 0.1, -0.2, 0.4, -0.1, 0.1, -0.1, -0.1], [0.0, -0.4, 0.2, 0.0, -0.2, -0.1, 0.0, 0.2, 0.2, 0.0, -0.5, 0.3], [0.1, 0.1, -0.2, 0.2, -0.4, 0.1, 0.0, -0.1, 0.1, -0.2, -0.2, -0.2], [0.0, -0.2, 0.2, -0.2, 0.0, -0.1, -0.1, 0.4, -0.1, 0.2, 0.2, 0.2], [-0.1, -0.3, -0.3, -0.2, 0.3, 0.1, 0.4, -0.2, 0.1, 0.2, -0.2, -0.4], [-0.2, 0.1, 0.2, 0.3, 0.4, 0.3, -0.1, -0.1, 0.2, -0.1, 0.3, 0.3], [-0.1, -0.2, 0.2, 0.0, 0.2, -0.2, -0.3, -0.2, -0.3, -0.2, 0.0, -0.4], [0.2, -0.1, 0.3, 0.4, 0.1, -0.1, -0.1, 0.4, 0.1, 0.1, 0.1, -0.5], [-0.4, 0.4, 0.3, 0.1, 0.2, 0.2, -0.1, -0.1, -0.2, 0.3, -0.3, -0.2], [0.1, -0.1, 0.0, -0.2, -0.1, 0.6, -0.4, 0.0, 0.4, 0.0, -0.1, -0.2]])
S = np.array([[37,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0, 33,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0, 28,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0, 26,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2]])
V = np.array([[-0.1, 0.0, -0.4, 0.0, 0.3, 0.1, 0.2, 0.5, 0.3, -0.1, -0.6, -0.1], [-0.5, -0.4, 0.2, -0.2, -0.6, -0.1, 0.2, 0.3, 0.0, 0.1, -0.2, 0.0], [0.0, -0.4, -0.2, 0.3, -0.1, 0.6, 0.0, -0.2, -0.3, -0.3, -0.2, 0.1], [0.2, 0.0, -0.4, -0.3, -0.3, -0.2, 0.2, -0.4, 0.2, -0.5, 0.0, -0.2], [-0.6, 0.4, 0.3, 0.0, 0.1, 0.1, -0.1, -0.3, 0.2, -0.4, -0.1, 0.3], [-0.2, -0.1, 0.1, 0.6, 0.2, -0.4, 0.5, -0.1, -0.1, -0.1, 0.0, -0.3], [-0.1, -0.4, 0.0, -0.4, 0.6, -0.2, 0.1, 0.1, -0.2, -0.2, 0.2, 0.3], [0.0, 0.1, 0.0, -0.1, 0.0, 0.5, 0.6, 0.1, 0.3, 0.1, 0.5, 0.0], [-0.5, 0.1, -0.6, -0.1, 0.1, 0.0, -0.1, -0.2, -0.3, 0.4, 0.1, -0.2], [0.1, 0.5, -0.1, -0.1, -0.2, 0.0, 0.3, 0.3, -0.6, -0.1, -0.1, 0.3], [0.2, 0.0, 0.1, -0.1, 0.1, 0.0, 0.4, -0.5, 0.0, 0.5, -0.5, 0.3], [0.0, -0.1, -0.4, 0.4, -0.2, -0.3, -0.1, 0.1, 0.2, 0.1, 0.2, 0.7]])

In [48]:
a,b=U.shape
U.reshape(a*b,)

array([-0.3, -0.2, -0.2,  0.5,  0. ,  0. ,  0.1, -0.2,  0.1,  0.2,  0. ,
        0.2, -0.3, -0.2,  0. ,  0.1,  0.1,  0.4,  0.3,  0.4, -0.3, -0.6,
       -0.1,  0. , -0.2, -0.3, -0.1, -0.1, -0.3,  0.1,  0. , -0.1,  0. ,
       -0.1,  0.5, -0.2,  0. , -0.3, -0.3, -0.1,  0.5, -0.1, -0.3,  0. ,
        0.2,  0. , -0.1,  0.1, -0.3, -0.3, -0.1,  0. , -0.3,  0.1, -0.4,
       -0.1, -0.4,  0.3, -0.1,  0.2, -0.5,  0.1, -0.1,  0. , -0.1, -0.4,
       -0.3,  0. ,  0.4, -0.3, -0.1, -0.1,  0.3,  0. ,  0.2, -0.1,  0.1,
        0. , -0.2, -0.4, -0.3, -0.3, -0.3,  0.1, -0.1, -0.2,  0.5, -0.2,
       -0.1,  0.1,  0.2, -0.2,  0.2,  0.1, -0.1,  0. , -0.3,  0.2,  0.2,
       -0.5,  0. , -0.2,  0.2,  0. ,  0.2, -0.1,  0. ,  0. , -0.1,  0.3,
       -0.3, -0.2,  0.1,  0.1, -0.2,  0.4, -0.1,  0.1, -0.1, -0.1,  0. ,
       -0.4,  0.2,  0. , -0.2, -0.1,  0. ,  0.2,  0.2,  0. , -0.5,  0.3,
        0.1,  0.1, -0.2,  0.2, -0.4,  0.1,  0. , -0.1,  0.1, -0.2, -0.2,
       -0.2,  0. , -0.2,  0.2, -0.2,  0. , -0.1, -0

In [49]:
c=np.array([[0.,0.,0.5,0.,0.5],[1/3,0.,1/3,0.,1/3],[1/3,0.,0.,1/3,1/3],[1/2,1/2,0.,0.,0.],[1/3,1/3,0.,1/3,0.]])

In [64]:
c

array([[0.        , 0.        , 0.5       , 0.        , 0.5       ],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.33333333],
       [0.33333333, 0.        , 0.        , 0.33333333, 0.33333333],
       [0.5       , 0.5       , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.        , 0.33333333, 0.        ]])

In [63]:
p=[0.45,0,0.55,0,0]
for i in range(10000):
    p=c@p
sum(p)

1.1134020618556681

In [33]:
S[:k,:k].shape

(10, 10)

AttributeError: module 'numpy.linalg' has no attribute 'flatt'

In [40]:
U.shape

(19, 12)

In [35]:
k=10
U[:,:k]@S[:k,:k]@(V.T)[:k,:]

array([[ 2.840e+00,  4.310e+00,  7.410e+00, -3.500e+00,  2.380e+00,
         1.059e+01, -1.890e+00, -1.190e+00,  7.440e+00, -5.870e+00,
        -2.280e+00,  8.100e+00],
       [ 4.380e+00,  6.870e+00,  8.350e+00, -4.320e+00,  4.680e+00,
         3.910e+00,  4.430e+00,  3.610e+00,  3.100e+00, -1.630e+00,
        -4.460e+00, -1.540e+00],
       [-2.900e-01,  1.111e+01,  5.760e+00,  2.680e+00, -3.700e-01,
        -1.230e+00,  1.480e+00, -2.000e-02,  3.910e+00, -4.010e+00,
        -2.060e+00,  1.740e+00],
       [ 6.310e+00, -4.230e+00,  2.320e+00,  8.600e-01, -4.970e+00,
        -1.700e-01,  1.136e+01, -2.960e+00,  5.290e+00, -7.790e+00,
        -6.800e-01,  2.200e+00],
       [-1.800e+00,  1.188e+01,  6.660e+00, -1.400e+00,  7.300e-01,
        -8.900e-01,  4.900e-01, -3.280e+00,  7.700e+00, -4.400e+00,
        -3.460e+00,  2.860e+00],
       [ 2.050e+00,  8.590e+00, -4.920e+00,  3.000e-01,  1.226e+01,
         3.770e+00,  7.000e-02, -4.210e+00,  9.780e+00, -1.880e+00,
        -6.300e+00,

In [13]:
sum((np.diag(S@S))[:4])/su

0.7899193548387097

In [14]:
(np.diag(S@S))[:4]

array([1369, 1089,  784,  676])

In [8]:
su=sum(np.diag(S@S))

### 5

In [37]:
M=19
N=14383

In [38]:
baseball_data=10000*np.random.randn(N,M)

In [51]:
M=M-1
baseball_data=baseball_data[:,1:]
l=[]
for i in range(M):
    l.append(baseball_data[:,i].mean())
X=(baseball_data-np.array(l))
U,s,Vt=la.svd(X,full_matrices=False)
p1=X@(Vt[0,:].T)
p2=X@(Vt[1,:].T)
cova=(X.T)@X/(N-1)
cov_age_runs=cova[0,7]
cov_stole_bases=cova[9,10]