In [1]:
import numpy as np
import numpy.linalg as la
import scipy.linalg as sla

In [2]:
A=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
b=np.array([1,2,3,4])

In [3]:
A_inv=la.inv(A)

In [12]:
la.solve(A,b)

array([ 0.  ,  0.  , -0.  ,  0.25])

In [10]:
#解LU
P,L,U=sla.lu(A)

In [19]:
y=sla.solve_triangular(L,P.T@b,lower=True)#下三角对角矩阵
x=sla.solve_triangular(U,y)#默认上三角
x

array([ 0.  ,  0.  , -0.  ,  0.25])

In [7]:
np.tril(A)

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

In [8]:
np.triu(A)

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

In [21]:
np.eye(3,4)#获取对角标准矩阵

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [22]:
la.cond(A)#||A||*||A^-1||#矩阵A 的condition numbers, 越小越好，大于等于1

1.4154738090434995e+17

In [23]:
la.eig(A)#获取矩阵A的特征值与特征向量

(array([ 3.62093727e+01, -2.20937271e+00, -2.91421324e-15, -5.70557534e-16]),
 array([[-0.15115432,  0.72704996, -0.36400894,  0.00610215],
        [-0.34923733,  0.28320876,  0.79039305,  0.40008675],
        [-0.54732033, -0.16063243, -0.4887593 , -0.81847996],
        [-0.74540333, -0.60447363,  0.06237518,  0.41229105]]))

In [13]:
import numpy as np
import numpy.linalg as la
n=4
s=np.array([1]+[0]*(n-1))

In [14]:
s

array([1, 0, 0, 0])