In [26]:
import numpy as np
import numpy.linalg as la

In [90]:
M=np.array([[0.6,0,0,0],[0.2,0.4,0.4,0],[0.1,0.3,0.5,0],[0.1,0.3,0.1,1]])
A=np.array([1,0,0,0])

In [10]:
hours=0
while A[3]<=0.8:
    A=M@A
    hours+=1

In [12]:
hours

9

In [21]:
import numpy as np
mat=np.array([[0,0.5,0.5,0,0],[0.25,0,0.5,0,1],[0.25,0,0,0.5,0],[0.25,0.5,0,0,0],[0.25,0,0,0.5,0]])
prob=np.array([10/46,13/46,7/46,9/46,7/46])

In [24]:
mat@prob

array([0.2173913 , 0.2826087 , 0.15217391, 0.19565217, 0.15217391])

In [27]:
la.inv(M)

array([[ 1.66666667,  0.        ,  0.        ,  0.        ],
       [-1.25      ,  6.25      , -5.        ,  0.        ],
       [ 0.41666667, -3.75      ,  5.        , -0.        ],
       [ 0.16666667, -1.5       ,  1.        ,  1.        ]])

In [42]:
M

array([[0.6, 0. , 0. , 0. ],
       [0.2, 0.4, 0.4, 0. ],
       [0.1, 0.3, 0.5, 0. ],
       [0.1, 0.3, 0.1, 1. ]])

In [62]:
np.delete(M,2,0)#2表示index, 0表示删除行

array([[0.6, 0. , 0. , 0. ],
       [0.2, 0.4, 0.4, 0. ],
       [0.1, 0.3, 0.1, 1. ]])

In [91]:
A=M.copy()
comp1=np.array([0.5,0.3,0.2,0])
comp2=A@comp1
A[2,:]=np.array([0]*4)
A[:,2]=np.array([0]*4)

In [92]:
A

array([[0.6, 0. , 0. , 0. ],
       [0.2, 0.4, 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0.1, 0.3, 0. , 1. ]])

In [93]:
c_n=A@comp1
d=comp2-c_n
r=2
c=2
A_complete=A.copy()
A_complete[:,c]=d/comp1[c]
A_n=sum(np.delete(A_complete,r,0))
A_complete[r,:]=np.array([1]*4)-A_n

In [94]:
M

array([[0.6, 0. , 0. , 0. ],
       [0.2, 0.4, 0.4, 0. ],
       [0.1, 0.3, 0.5, 0. ],
       [0.1, 0.3, 0.1, 1. ]])

In [95]:
A_complete

array([[0.6, 0. , 0. , 0. ],
       [0.2, 0.4, 0.4, 0. ],
       [0.1, 0.3, 0.5, 0. ],
       [0.1, 0.3, 0.1, 1. ]])

In [75]:
c_n

array([0.6, 0.2, 0. , 0.1])

In [77]:
comp2

array([0.6, 0.2, 0. , 0.1])

In [29]:
B=np.array([1,0,0,0])

In [38]:
A==B

array([False, False,  True, False])

In [37]:
(A==B).all()

False

In [39]:
(A==B).any()

True

In [98]:
max(abs(np.array([-0.5,0.7])))

0.7