In [1]:
import numpy as np

In [ ]:
team_names = [ ... ]    # list team names here
A = ...                 # the rows and columns should have the same order as your team_names

In [18]:
home_team=np.array(['Philadelphia 76ers','Oklahoma City Thunder', 'Milwaukee Bucks'
 'Brooklyn Nets' ,'New Orleans Pelicans', 'Memphis Grizzlies',
 'Denver Nuggets', 'Atlanta Hawks', 'Miami Heat', 'Dallas Mavericks'])

In [3]:
away_team=np.array(['Boston Celtics' ,'Golden State Warriors', 'Charlotte Hornets',
 'Detroit Pistons' ,'Houston Rockets' ,'Indiana Pacers',
 'Los Angeles Clippers', 'New York Knicks', 'Orlando Magic', 'Phoenix Suns'])

In [4]:
home_score=np.array([ 87. ,100., 113. ,100., 131. , 83. ,107. ,107. ,101. ,100.])

In [5]:
away_score=np.array([105., 108., 112., 103., 112., 111.,  98., 126., 104., 121.])

In [56]:
net_score=home_score-away_score
net_score

array([-18.,  -8.,   1.,  -3.,  19., -28.,   9., -19.,  -3., -21.])

In [17]:
h_i=np.where(home_team=='New Orleans Pelicans')
away_team[h_i]

array(['Detroit Pistons', 'Phoenix Suns'], dtype='<U21')

In [7]:
list(set(home_team)).index('New Orleans Pelicans')

0

In [22]:
net_score=home_score-away_score
team_names=list(set(home_team))#队名
n=len(team_names)
A=np.array([0.]*n**2).reshape(n,n)#建立初始空矩阵
p=-1
for i in team_names:
    #按行循环
    p+=1
    h_i=np.where(home_team==i)#找出主队是i的场次
    t1=away_team[h_i]#找出此时客队的名称
    for j in range(len(t1)):
        q=team_names.index(t1[j])#找出客队的index
        net=net_score[h_i[0][j]]#净胜分
        if net>0:
            A[p,q]+=net
        else:
            A[q,p]-=net

ValueError: 'Detroit Pistons' is not in list

In [63]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.where(home_team=='New Orleans Pelicans')[0][0]

3

In [23]:
import random

In [30]:
[random.random() for i in range(10)]

[0.0475470359490866,
 0.4831118835098118,
 0.2979714332395884,
 0.26085047096773184,
 0.08632638249759328,
 0.5500923380802859,
 0.14466522616007738,
 0.023887117149313797,
 0.8208180242434198,
 0.33044267761184376]

In [53]:
x=np.array([1,2,5,6,8,2,3,5])
index=list(np.argsort(x))
index.reverse()
x[index]

array([8, 6, 5, 5, 3, 2, 2, 1])