In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
t=np.array([2.84800, -3.29410, 2.66020, 3.72210])

In [17]:
np.hstack(((t**2).reshape(4,1),t.reshape(4,1)))

array([[ 8.111104  ,  2.848     ],
       [10.85109481, -3.2941    ],
       [ 7.07666404,  2.6602    ],
       [13.85402841,  3.7221    ]])

In [2]:
A = np.array([[2.84800, -3.29410, 2.66020, 3.72210], [1.19520, 3.78810, -1.26500, 3.51830], [0.17480, 2.92780, 3.66720, 2.47100], [1.05520, -0.24520, -0.30480, 4.21000]])
X = np.array([[-0.35000, 0.21000, 0.18000, -0.90000], [-0.13000, -0.94000, -0.21000, -0.21000], [-0.32000, 0.25000, -0.92000, 0.00000], [-0.87000, -0.03000, 0.29000, 0.39000]])
D = np.array([[64,  0,  0,  0], [ 0, 36,  0,  0], [ 0,  0, 16,  0], [ 0,  0,  0,  1]])

In [5]:
#水平组合
np.hstack((A,X))

array([[ 2.848 , -3.2941,  2.6602,  3.7221, -0.35  ,  0.21  ,  0.18  ,
        -0.9   ],
       [ 1.1952,  3.7881, -1.265 ,  3.5183, -0.13  , -0.94  , -0.21  ,
        -0.21  ],
       [ 0.1748,  2.9278,  3.6672,  2.471 , -0.32  ,  0.25  , -0.92  ,
         0.    ],
       [ 1.0552, -0.2452, -0.3048,  4.21  , -0.87  , -0.03  ,  0.29  ,
         0.39  ]])

In [6]:
np.concatenate((A,X),axis=1)

array([[ 2.848 , -3.2941,  2.6602,  3.7221, -0.35  ,  0.21  ,  0.18  ,
        -0.9   ],
       [ 1.1952,  3.7881, -1.265 ,  3.5183, -0.13  , -0.94  , -0.21  ,
        -0.21  ],
       [ 0.1748,  2.9278,  3.6672,  2.471 , -0.32  ,  0.25  , -0.92  ,
         0.    ],
       [ 1.0552, -0.2452, -0.3048,  4.21  , -0.87  , -0.03  ,  0.29  ,
         0.39  ]])

In [7]:
#垂直组合
np.vstack((A,X))

array([[ 2.848 , -3.2941,  2.6602,  3.7221],
       [ 1.1952,  3.7881, -1.265 ,  3.5183],
       [ 0.1748,  2.9278,  3.6672,  2.471 ],
       [ 1.0552, -0.2452, -0.3048,  4.21  ],
       [-0.35  ,  0.21  ,  0.18  , -0.9   ],
       [-0.13  , -0.94  , -0.21  , -0.21  ],
       [-0.32  ,  0.25  , -0.92  ,  0.    ],
       [-0.87  , -0.03  ,  0.29  ,  0.39  ]])

In [8]:
np.concatenate((A,X),axis=0)

array([[ 2.848 , -3.2941,  2.6602,  3.7221],
       [ 1.1952,  3.7881, -1.265 ,  3.5183],
       [ 0.1748,  2.9278,  3.6672,  2.471 ],
       [ 1.0552, -0.2452, -0.3048,  4.21  ],
       [-0.35  ,  0.21  ,  0.18  , -0.9   ],
       [-0.13  , -0.94  , -0.21  , -0.21  ],
       [-0.32  ,  0.25  , -0.92  ,  0.    ],
       [-0.87  , -0.03  ,  0.29  ,  0.39  ]])