In [1]:
import numpy as np

In [107]:
K=np.array([[20,10,-10,0,-10,-10],[10,10,0,0,-10,-10],[-10,0,20,-10,-10,10],[0,0,-10,10,10,-10],[-10,-10,-10,10,20,0],[-10,-10,10,-10,0,20]])

In [17]:
equation_numbers=np.array([1,2,4,3,5,6])

In [23]:
K.T

array([[ 20,  10, -10,   0, -10, -10],
       [ 10,  10,   0,   0, -10, -10],
       [-10,   0,  20, -10, -10,  10],
       [  0,   0, -10,  10,  10, -10],
       [-10, -10, -10,  10,  20,   0],
       [-10, -10,  10, -10,   0,  20]])

In [29]:
def reorder_rows_columns(K,equation_numbers):
    # construct the matrix Khat
    Khat=[]
    K_m=[]
    for i in equation_numbers:
        K_m.append(K[i-1,:])
    K_m=np.array(K_m)
    for j in equation_numbers:
        Khat.append(K_m[:,j-1])
    return np.array(Khat).T

In [30]:
reorder_rows_columns(K,equation_numbers)

array([[ 20,  10,   0, -10, -10, -10],
       [ 10,  10,   0,   0, -10, -10],
       [  0,   0,  10, -10,  10, -10],
       [-10,   0, -10,  20, -10,  10],
       [-10, -10,  10, -10,  20,   0],
       [-10, -10, -10,  10,   0,  20]])

In [31]:
def partition_stiffness_matrix(K,equation_numbers,nk):
    # construct the smaller matrices
    Khat=reorder_rows_columns(K,equation_numbers)
    Kpp=Khat[:nk,:nk]
    Kpf=Khat[:nk,nk:]
    Kfp=Khat[nk:,:nk]
    Kff=Khat[nk:,nk:]
    return  Kpp,Kpf,Kfp,Kff

In [32]:
partition_stiffness_matrix(K,equation_numbers,3)

(array([[20, 10,  0],
        [10, 10,  0],
        [ 0,  0, 10]]),
 array([[-10, -10, -10],
        [  0, -10, -10],
        [-10,  10, -10]]),
 array([[-10,   0, -10],
        [-10, -10,  10],
        [-10, -10, -10]]),
 array([[ 20, -10,  10],
        [-10,  20,   0],
        [ 10,   0,  20]]))

In [33]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
xp=np.array([0,0,0])
Ff=np.array([0,0,-10])
Kpp,Kpf,Kfp,Kff=partition_stiffness_matrix(K,equation_numbers,3)
def fea_solve(Kpp,Kpf,Kfp,Kff,xp,Ff):
    # do stuff here
    xf=la.solve(Kff,Ff-np.dot(Kfp,xp))
    Fp=np.dot(Kpp,xp)+np.dot(Kpf,xf)
    return xf,Fp

In [34]:
fea_solve(Kpp,Kpf,Kfp,Kff,xp,Ff)

(array([ 0.5 ,  0.25, -0.75]), array([0., 5., 5.]))

In [37]:
x=np.array([0]*16).reshape(4,4)

In [38]:
len(x)

4

In [49]:
s=K.copy()
s[1,:]=np.array([1,2,3,4,5,6])

In [50]:
s

array([[ 20,  10, -10,   0, -10, -10],
       [  1,   2,   3,   4,   5,   6],
       [-10,   0,  20, -10, -10,  10],
       [  0,   0, -10,  10,  10, -10],
       [-10, -10, -10,  10,  20,   0],
       [-10, -10,  10, -10,   0,  20]])

In [100]:
K

array([[ 20,  10, -10,   0, -10, -10],
       [ 10,  10,   0,   0, -10, -10],
       [-10,   0,  20, -10, -10,  10],
       [  0,   0, -10,  10,  10, -10],
       [-10, -10, -10,  10,  20,   0],
       [-10, -10,  10, -10,   0,  20]])

In [117]:
la.lu(K)

(array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]),
 array([[ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0.5,  1. ,  0. ,  0. ,  0. ,  0. ],
        [-0.5,  1. ,  1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. , -1. ,  1. ,  0. ,  0. ],
        [-0.5, -1. , -1. ,  0. ,  1. ,  0. ],
        [-0.5, -1. ,  1. ,  0. ,  0. ,  1. ]]),
 array([[ 20.,  10., -10.,   0., -10., -10.],
        [  0.,   5.,   5.,   0.,  -5.,  -5.],
        [  0.,   0.,  10., -10., -10.,  10.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.]]))

In [183]:
b=np.array([1,2])
L=np.array([[1,0],[2,3]])
l=2
y=np.array([0.]*l).reshape(l,)
for i in range(l):
    s=b[i]
    for j in range(i):
        s-=L[i,j]*y[j]
    y[i]=s/L[i,i]

In [184]:
y

array([1., 0.])

In [185]:
import numpy as np


def my_lu(A):
    # The upper triangular matrix U is saved in the upper part of the matrix M (including the diagonal)
    # The lower triangular matrix L is saved in the lower part of the matrix M (not including the diagonal)
    # Do NOT use `scipy.linalg.lu`!
    # You should not use pivoting
    l=len(A)
    t=A.copy()
    M=np.array([0.]*(l**2)).reshape(l,l)
    for i in range(l-1):
        M[i,i:]=t[0,:]
        M[i+1:,i]=t[1:,0]/t[0,0]
        t=t[1:,1:]-np.dot(M[i+1:,i].reshape(l-1-i,1),t[0,1:].reshape(1,l-1-i))
    M[l-1,l-1]=t
    return np.nan_to_num(M)


def my_triangular_solve(M, b):
    # A = LU (L and U are stored in M)
    l=len(M)
    L=np.array([0.]*(l**2)).reshape(l,l)
    U=np.array([0.]*(l**2)).reshape(l,l)
    for i in range(l):
        L[i,i]=1
        L[i+1:,i]=M[i+1:,i]
        U[i,i:]=M[i,i:]
    # A x = b (given A and b, find x)
    #Ly=b,Ux=y
    y=np.array([0.]*l).reshape(l,)
    for i in range(l):
        s=b[i]
        for j in range(i):
            s-=L[i,j]*y[j]
        y[i]=s/L[i,i]
    x=np.array([0.]*l).reshape(l,)
    for i in range(l-1,-1,-1):
        s=y[i]
        for j in range(l-1,i,-1):
            s-=U[i,j]*x[j]
        x[i]=s/U[i,i]
    # M is a 2D numpy array
    # The upper triangular matrix U is stored in the upper part of the matrix M (including the diagonal)
    # The lower triangular matrix L is stored in the lower part of the matrix M (not including the diagonal)
    # b is a 1D numpy array
    # x is a 1D numpy array
    # Do not use `scipy.linalg.solve_triangular`

    return x


def fea_solve(Kpp, Kpf, Kfp, Kff, xp, Ff):
    # Use my_lu and my_triangular_solve
    M=my_lu(Kff)
    xf=my_triangular_solve(M,Ff-np.dot(Kfp,xp))
    Fp=np.dot(Kpp,xp)+np.dot(Kpf,xf)
    return xf, Fp