In [1]:
import numpy as np
import numpy.linalg as la
import sympy as sp
import math

In [2]:
def Bisection(a,b,tol,maxiter):
    for i in range(maxiter):
        m=(a+b)/2
        print(m)
        if f(m)*f(a)>0:
            a=m
        else:
            b=m
        if abs(f(m))<tol:
            return m,i+1

In [3]:
Bisection(-2,2,1e-5,1000)

0.0


NameError: name 'f' is not defined

In [128]:
x=sp.var('x')
x

x

In [136]:
y=x**3+2*x-9

In [137]:
y

x**3 + 2*x - 9

In [138]:
y.diff(x)

3*x**2 + 2

In [132]:
def f(a):
    return float(y.subs(x,a))
def df(a):
    return float(y.diff(x).subs(x,a))

In [44]:
df(1)

0.0

In [47]:
def Newton(x0,tol,maxiter):
    xnew=x0
    for i in range(maxiter):
        xold=xnew
        xnew=xold-f(xold)/df(xold)
        print(xnew)
        if abs(f(xnew))<tol:
            return xnew,i+1

In [139]:
Newton(0,1e-5,10)

4.5
3.047808764940239
2.197144764443793
1.833064968446342
1.7647342327842843
1.7624987129175251
1.7624963764579105


(1.7624963764579105, 7)

In [133]:
def Secant(x1,x2,tol,maxiter):
    for i in range(maxiter):
        d=(f(x1)-f(x2))/(x1-x2)
        print(d)
        xnew=x2-f(x2)/d
        print(xnew)
        if abs(f(xnew))<tol:
            return xnew,i+1
        x1=x2
        x2=xnew

In [135]:
Secant(1,0,1e-5,10)

-1.0
8.0
62.0
-0.12903225806451601
60.984391259105095
-0.26440978739378207
-1.879320748787366
4.263999757164432
15.12416319552897
-0.8271076309750285
13.339014224689086
-1.5084462187659358
2.207164406583105
-4.944782366606592
32.18522091154093
-1.7440996839204703
34.116949723209046
-1.9253248815220576
8.106718124166251
-2.506782049392239


In [62]:
x1=sp.var('x1')
x2=sp.var('x2')

In [118]:
f1=(1)*(x1**2)+(-3)*(x1)+(0)*(1)+(-3)*(x2**2)+(-1)*(x2)+(-1)*(x1*x2)
f2=(-2)*(x1**2)+(-1)*(x1)+(-2)*(1)+(0)*(x2**2)+(-2)*(x2)+(0)*(x1*x2)
df11=f1.diff(x1)
df12=f1.diff(x2)
df21=f2.diff(x1)
df22=f2.diff(x2)

In [119]:
print(f1)
print(f2)
print(df11)
print(df12)
print(df21)
print(df22)

x1**2 - x1*x2 - 3*x1 - 3*x2**2 - x2
-2*x1**2 - x1 - 2*x2 - 2
2*x1 - x2 - 3
-x1 - 6*x2 - 1
-4*x1 - 1
-2


In [120]:
def F_f1(a,b):
    return float(f1.subs(x1,a).subs(x2,b))
def F_f2(a,b):
    return float(f2.subs(x1,a).subs(x2,b))
def F_df11(a,b):
    return float(df11.subs(x1,a).subs(x2,b))
def F_df12(a,b):
    return float(df12.subs(x1,a).subs(x2,b))
def F_df21(a,b):
    return float(df21.subs(x1,a).subs(x2,b))
def F_df22(a,b):
    return float(df22.subs(x1,a).subs(x2,b))

In [110]:
F_df11(1,2)

6.0

In [124]:
def system_Newton(xnew,tol,maxiter):
    for i in range(maxiter):
        xold=xnew
        a=xold[0]
        b=xold[1]
        J=np.array([[F_df11(a,b),F_df12(a,b)],[F_df21(a,b),F_df22(a,b)]])
        print(J)
        f=np.array([F_f1(a,b),F_f2(a,b)])
        if sum(abs(f))<tol:
            return xnew,i
        s=la.solve(J,-f)
        xnew=s+xold
        print(xnew)

In [125]:
x=np.array([0,2])
system_Newton(x,1e-5,10)

[[ -5. -13.]
 [ -1.  -2.]]
[-16.66666667   7.33333333]
[[-43.66666667 -28.33333333]
 [ 65.66666667  -2.        ]]
[-8.29688362  4.3634324 ]
[[-23.95719963 -18.88371076]
 [ 32.18753446  -2.        ]]
[-4.05335079  2.60459361]
[[-13.71129519 -12.57421087]
 [ 15.21340316  -2.        ]]
[-1.83478205  1.47301313]
[[-8.14257722 -8.00329672]
 [ 6.33912819 -2.        ]]
[-0.55205125  0.61666335]
[[-4.72076584 -4.14792883]
 [ 1.20820499 -2.        ]]
[ 0.4676421  -0.41273566]
[[-1.65198014  1.00877186]
 [-2.87056839 -2.        ]]
[-0.22220848 -0.46237855]
[[-2.98203841  1.99647977]
 [-0.11116608 -2.        ]]
[-0.38899041 -0.92900212]
[[-2.8489787   4.96300314]
 [ 0.55596165 -2.        ]]
[-0.96153449 -1.11597461]
[[-3.80709438  6.65738216]
 [ 2.84613797 -2.        ]]
[-0.59687598 -0.92484712]


In [13]:
def system_Newton(xnew,tol,maxiter):
    for i in range(maxiter):
        xold=xnew
        a=xold[0]
        b=xold[1]
        j=J(a,b)
        fv=f(a,b)
        r=la.norm(fv,2)
        if r<tol:
            return xnew,r
        s=la.solve(j,-fv)
        xnew=s+xold
    return xnew,r

In [4]:
def system_Newton(xi,tol):
    xo=xi
    a=xo[0]
    b=xo[1]
    while la.norm(f(xo),2)>tol:
        s=la.solve(J,-f)
        xo=s+xo
    return xo,la.norm(f(xo),2)

In [11]:
J=np.array([[6.,6.],[-24.,5.]])
f=np.array([-5.,6.])
np.array([-1,1])+la.solve(J,-f)

array([-0.64942529,  1.48275862])

In [10]:
J

array([[  6.,   6.],
       [-24.,   5.]])