In [49]:
import numpy as np
import numpy.linalg as la

In [14]:
U=np.array([[-0.28,0.12,-0.95],[-0.17,-0.98,-0.08],[-0.95,0.14,0.29]])

In [15]:
U

array([[-0.28,  0.12, -0.95],
       [-0.17, -0.98, -0.08],
       [-0.95,  0.14,  0.29]])

In [24]:
sp=np.array([[1/7,0,0],[0,1/5,0],[0,0,0],[0,0,0]])

In [25]:
sp

array([[0.14285714, 0.        , 0.        ],
       [0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [20]:
V=np.array([[-0.26,0.87,0.36,0.2],[-0.64,-0.47,0.51,0.33],[-0.66,0.08,-0.32,-0.67],[-0.29,0.06,-0.71,0.63]])

In [26]:
V

array([[-0.26,  0.87,  0.36,  0.2 ],
       [-0.64, -0.47,  0.51,  0.33],
       [-0.66,  0.08, -0.32, -0.67],
       [-0.29,  0.06, -0.71,  0.63]])

In [27]:
V@sp@U.T

array([[ 0.03128   , -0.16420571,  0.05964571],
       [ 0.01432   ,  0.10766286,  0.07369714],
       [ 0.02832   ,  0.00034857,  0.09181143],
       [ 0.01304   , -0.00471714,  0.04103714]])

In [28]:
la.svd(U)

(array([[-0.49026111, -0.4084545 , -0.76994089],
        [-0.25500115, -0.77751412,  0.5748445 ],
        [-0.83343774,  0.47815971,  0.27702857]]),
 array([1.00540077, 0.99908734, 0.99407936]),
 array([[ 0.96716572,  0.07398892,  0.24313807],
        [-0.20789681,  0.78060409,  0.58943717],
        [-0.14618275, -0.62063105,  0.77035557]]))

In [43]:
la.svd(sp)

(array([[0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([0.2       , 0.14285714, 0.        ]),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]))

Returns
u{ (…, M, M), (…, M, K) } array
Unitary array(s). The first a.ndim - 2 dimensions have the same size as those of the input a. The size of the last two dimensions depends on the value of full_matrices. Only returned when compute_uv is True.

s(…, K) array
Vector(s) with the singular values, within each vector sorted in descending order. The first a.ndim - 2 dimensions have the same size as those of the input a.

vh{ (…, N, N), (…, K, N) } array
Unitary array(s). The first a.ndim - 2 dimensions have the same size as those of the input a. The size of the last two dimensions depends on the value of full_matrices. Only returned when compute_uv is True.

In [48]:
np.diag(s)

array([[0.2       , 0.        , 0.        ],
       [0.        , 0.14285714, 0.        ],
       [0.        , 0.        , 0.        ]])

In [51]:
sp

array([[0.14285714, 0.        , 0.        ],
       [0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [52]:
U,s,VT=la.svd(sp)
U@np.diag(s)@VT

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [30]:
la.svd(sp,full_matrices=False)

(array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 0., 0.]]),
 array([0.2       , 0.14285714, 0.        ]),
 array([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.]]))

In [77]:
U,s,VT=la.svd(sp,full_matrices=False)
U@np.diag(s)@VT

array([[0.14285714, 0.        , 0.        ],
       [0.        , 0.2       , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [78]:
U

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [103]:
VT

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [102]:
U[:,:k]@np.diag(s[:k])

array([[0. ],
       [0.2],
       [0. ],
       [0. ]])

In [104]:
k=1
U[:,:k]@np.diag(s[:k])@VT[:k,:]

array([[0. , 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ]])

In [68]:
s.sort()

In [69]:
s

array([0.        , 0.14285714, 0.2       ])

In [73]:
s[::-1]

array([0.2       , 0.14285714, 0.        ])

In [74]:
np.linspace(1,50,50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [111]:
def lst_sq(A, b):
    """
    Solve the least square equation using SVD
    """
    # Your code here
    U,s,VT=la.svd(A,full_matrices=False)
    s[s>0]=1/s[s>0]
    return VT.T@np.diag(s)@U.T@b